name: Test docker image
on: pull_request
env:
  DOCKER_BUILDKIT: 1
  DATABASE_URL: sqlite:///
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update pip
      run: pip install setuptools --upgrade
    - name: Build image
      run: docker build --tag ubuntu-com .
    - name: Run image
      run: |
        docker run -d -p 80:80 ubuntu-com
        sleep 1 && curl --head --fail --retry-delay 5 --retry 10  --retry-connrefused http://localhost
